services:
  web:
      build: .
      container_name: milliavod
      env_file: 
        - .prod.env
      ports:
        - "8000:5000"
      restart: unless-stopped
      depends_on: 
        - db
  db:
      image: mariadb:latest
      container_name: mysql
      env_file:
        - .db.env
      restart: unless-stopped
      volumes: 
        - db_data:/var/lib/mysql

volumes:
  db_data: