services:
  web:
      build: .
      container_name: milliavod
      ports: 
        - 8000:5000
      env_file: 
        - .prod.env
      restart: unless-stopped
      depends_on: 
        - db
  db:
      image: mariadb:latest
      container_name: mysql
      env_file:
        - .db.env
      restart: unless-stopped
      volumes: 
        - db_data:/var/lib/mysql
      command:
        --innodb_use_native_aio=OFF

volumes:
  db_data: