"""initial migration

Revision ID: 6773617a3159
Revises: 
Create Date: 2025-07-02 17:38:34.726269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6773617a3159'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_vod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.Column('p1name', sa.String(length=64), nullable=False),
    sa.Column('p2character', sa.String(length=64), nullable=False),
    sa.Column('p2name', sa.String(length=64), nullable=False),
    sa.Column('timesubmitted', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('timeverified', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_vod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_vod_link'), ['link'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_vod_p1name'), ['p1name'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_vod_p2character'), ['p2character'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_vod_p2name'), ['p2name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_vod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_vod_p2name'))
        batch_op.drop_index(batch_op.f('ix_match_vod_p2character'))
        batch_op.drop_index(batch_op.f('ix_match_vod_p1name'))
        batch_op.drop_index(batch_op.f('ix_match_vod_link'))

    op.drop_table('match_vod')
    # ### end Alembic commands ###
