"""resetting commit

Revision ID: ebe4299aff47
Revises: 
Create Date: 2025-07-14 19:03:05.187163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe4299aff47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.Column('p1name', sa.String(length=64), nullable=False),
    sa.Column('p2character', sa.String(length=64), nullable=False),
    sa.Column('p2name', sa.String(length=64), nullable=False),
    sa.Column('timesubmitted', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('timeverified', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matchvod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchvod_link'), ['link'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchvod_p1name'), ['p1name'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchvod_p2character'), ['p2character'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchvod_p2name'), ['p2name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matchvod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchvod_id'], ['matchvod.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'matchvod_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('matchvod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchvod_p2name'))
        batch_op.drop_index(batch_op.f('ix_matchvod_p2character'))
        batch_op.drop_index(batch_op.f('ix_matchvod_p1name'))
        batch_op.drop_index(batch_op.f('ix_matchvod_link'))

    op.drop_table('matchvod')
    # ### end Alembic commands ###
