"""Favoriting

Revision ID: ff332f965943
Revises: 8773e94a8149
Create Date: 2025-07-07 23:30:45.999334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff332f965943'
down_revision = '8773e94a8149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.Column('p1name', sa.String(length=64), nullable=False),
    sa.Column('p2character', sa.String(length=64), nullable=False),
    sa.Column('p2name', sa.String(length=64), nullable=False),
    sa.Column('timesubmitted', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('timeverified', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matchvod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchvod_link'), ['link'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchvod_p1name'), ['p1name'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchvod_p2character'), ['p2character'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchvod_p2name'), ['p2name'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matchvod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchvod_id'], ['matchvod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'matchvod_id')
    )
    with op.batch_alter_table('match_vod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_vod_link'))
        batch_op.drop_index(batch_op.f('ix_match_vod_p1name'))
        batch_op.drop_index(batch_op.f('ix_match_vod_p2character'))
        batch_op.drop_index(batch_op.f('ix_match_vod_p2name'))

    op.drop_table('match_vod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_vod',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=128), nullable=False),
    sa.Column('p1name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('p2character', sa.VARCHAR(length=64), nullable=False),
    sa.Column('p2name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('timesubmitted', sa.DATETIME(), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=False),
    sa.Column('timeverified', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_vod', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_vod_p2name'), ['p2name'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_vod_p2character'), ['p2character'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_vod_p1name'), ['p1name'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_vod_link'), ['link'], unique=False)

    op.drop_table('favorites')
    with op.batch_alter_table('matchvod', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchvod_p2name'))
        batch_op.drop_index(batch_op.f('ix_matchvod_p2character'))
        batch_op.drop_index(batch_op.f('ix_matchvod_p1name'))
        batch_op.drop_index(batch_op.f('ix_matchvod_link'))

    op.drop_table('matchvod')
    # ### end Alembic commands ###
